services:
  postgres: 
    image: postgres:14.3-alpine3.16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: autoservico
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - backend-postgres
 
  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=dynamodb,sqs
      - AWS_ACCESS_KEY_ID=localstack
      - AWS_SECRET_ACCESS_KEY=localstack
      - KINESIS_PROVIDER=kinesalite
      - DEFAULT_REGION=us-east-1
    ports:
      - '4566:4566'
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  data:
    external: true
networks:
  backend-postgres:
